import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import JobState from "./contexts/Job/JobState";
import UserState from "./contexts/User/UserState";
import { Toaster } from "@/components/ui/sonner";
import ApplicationState from "./contexts/Application/ApplicationState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <UserState>
            <JobState>
              <ApplicationState>
                {children}
                <Toaster richColors position="top-right" />
              </ApplicationState>
            </JobState>
          </UserState>
        </ThemeProvider>
      </body>
    </html>
  );
}
